branches:
  only:
    - "master"
gemfile:
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails50.gemfile
install:
  - 'travis_retry bundle install'
language:
  - ruby
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.4
  - 2.3.0
matrix:
  exclude:
    - rvm: 2.0.0-p648
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails50.gemfile
script: 'bundle exec rake spec'
notifications:
  email: false
sudo: false
cache: bundler
