gemfile:
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
install:
  - 'travis_retry bundle install'
language:
  - ruby
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.4
  - 2.3.0
script: 'bundle exec rake spec'
notifications:
  email: false
sudo: false
cache: bundler
