branches:
  only:
    - "master"
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
install:
  - 'travis_retry bundle install'
language:
  - ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
script: 'bundle exec rake spec'
notifications:
  email: false
sudo: false
cache: bundler
